version: '3'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./tmp:/app/config
  db:
    image: postgres:alpine
    env_file:
      - .env
  redis:
    image: redis:alpine